name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  flutter_native_splash: 2.4.0
  cloud_firestore: ^6.0.3
  provider: ^6.1.5+1
  intl: ^0.19.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/image_logo.jpg"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/image_logo.jpg
  android_12:
    color: "#ffffff"
    image: assets/images/image_logo.jpg
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/